sudo: false
language: node_js
node_js:
- 8
- node
cache:
  directories:
  - ~/.npm
  - node_modules
install:
  - npm install
script:
    - commitlint-travis
    - npm run build
    - npm run test
before_deploy:
- git config --global user.email "$(git log --pretty=format:"%ae" -n1)"
- git config --global user.name "$(git log --pretty=format:"%an" -n1)"
deploy:
- provider: npm
  on:
    branch: develop
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  script: npm run semantic-release
- provider: script
  on:
    all_branches: true
  skip_cleanup: true
  script: npm run deploy -- -x -e $TRAVIS_BRANCH -r https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
